name: test_TP2

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v3
      -
        name: install requirements
        run: cd TP2 && pip install -r requirements.txt
      -
        name: launch tests
        run: python -m unittest discover test
